name: call slack test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  send-api-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: hello
        run: echo "hello!!!!"
      - name: github infos
        run: echo ${{ github.head_ref }} 
        run: echo ${{ github.ref_name }} 
        run: echo ${{ github.event.repository.name }}
        run: echo ${{ github.sha }}
      - name: Send API Request
        run: |
          curl -X POST https://hooks.slack.com/triggers/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 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -d '{"eventTypeProduction ": "eventTypeProduction","eventTypeStaging ": "eventTypeStaging ","branch": "branch ","repository": "repository  ","commit": "commit  "}'

# jobs:
#   send-api-request:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       id-token: write

#       steps:
#         - name: hello
#           run: echo "hello!!!!"
#         - name: github infos
#           run: echo ${{ github.ref }}
#         - name: Send API Request
#           run: |
#             curl -X POST https://hooks.slack.com/triggers/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 \
#               -H "Content-Type: application/json" \
#               -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
#               -d '{"eventTypeProduction ": "eventTypeProduction","eventTypeStaging ": "eventTypeStaging ","branch": "branch ","repository": "repository  ","commit": "commit  "}'
