name: Called Workflow

on:
  workflow_call:
    inputs:
      example_input:
        description: "An example input"
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use the input
        run: echo "The input was ${{ inputs.example_input }}"
