name: Called Workflow

on:
  workflow_call:
    inputs:
      example_input:
        description: "An example input"
        required: true
        type: string
    secrets:
      THIS_IS_SECRET:
        description: Fill some secret string
        required: true
    outputs:
      greeting_message:
        description: Greeting message
        value: ${{ jobs.greeting.outputs.message }}

jobs:
  greeting:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.message.outputs.message }}
    steps:
      - id: message
        run: |
          echo 'message=Hooray ${{ inputs.friend_name }}!' >> $GITHUB_OUTPUT
