name: call another workflow

on:
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/called-workflow.yml
    with:
      example_input: myinput
    secrets:
      THIS_IS_SECRET: ${{ secrets.THIS_IS_SECRET }}

  show_outputs:
    needs:
      - call_reusable_workflow
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.call_reusable_workflow.outputs.greeting_message }}
