name: deploy

on:
  workflow_call:
    inputs:
      target:
        description: target environment
        required: true
        type: string
    secrets:
      SECRET:
        description: secret string
        required: true
    outputs:
      result:
        description: result message
        value: ${{ jobs.deploy.outputs.message }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.message.outputs.message }}
    # if: inputs.target == 'development'
    steps:
      # ここに既存のデプロイスクリプトを記述
      - name: deploy
        if: inputs.target == 'development'
        run: |
          echo 'deploying to ${{ inputs.target }}...'
      - id: message
        run: |
          echo 'message=${{ inputs.target }}!' >> $GITHUB_OUTPUT
