name: deploy to develop
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - hotfix/*
      - feature/*

jobs:
  call_deploy_schema: # schema
    uses: ./.github/workflows/deploy_common.yml
    with:
      target: development
    secrets:
      SECRET: ${{ secrets.SECRET }}

  call_deploy_api: # api
    needs:
      - call_deploy_schema
    uses: ./.github/workflows/deploy_common.yml
    with:
      target: development
    secrets:
      SECRET: ${{ secrets.SECRET }}

  call_deploy_frontend: # frontend
    needs:
      - call_deploy_schema
      - call_deploy_api
    uses: ./.github/workflows/deploy_common.yml
    with:
      target: development
    secrets:
      SECRET: ${{ secrets.SECRET }}

  call_deploy_receiver: # receiver
    needs:
      - call_deploy_schema
      - call_deploy_api
      - call_deploy_frontend
    uses: ./.github/workflows/deploy_common.yml
    with:
      target: development
    secrets:
      SECRET: ${{ secrets.SECRET }}

  call_deploy_uploader: # uploader
    needs:
      - call_deploy_schema
      - call_deploy_api
      - call_deploy_frontend
    uses: ./.github/workflows/deploy_common.yml
    with:
      target: development
    secrets:
      SECRET: ${{ secrets.SECRET }}

  call_deploy_ocr_request: # ocr-request
    needs:
      - call_deploy_schema
      - call_deploy_api
      - call_deploy_frontend
    uses: ./.github/workflows/deploy_common.yml
    with:
      target: development
    secrets:
      SECRET: ${{ secrets.SECRET }}

  call_deploy_ocr-result: # ocr-result
    needs:
      - call_deploy_schema
      - call_deploy_api
      - call_deploy_frontend
    uses: ./.github/workflows/deploy_common.yml
    with:
      target: development
    secrets:
      SECRET: ${{ secrets.SECRET }}

  send_api_request:
    needs:
      - call_deploy_schema
      - call_deploy_api
      - call_deploy_frontend
      - call_deploy_receiver
      - call_deploy_uploader
      - call_deploy_ocr_request
      - call_deploy_ocr-result
    runs-on: ubuntu-latest
    steps:
      - name: show result
        run: |
          echo ${{ needs.call_deploy_common.outputs.result }}

      - name: Send API Request
        run: |
          curl -X POST https://hooks.slack.com/triggers/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 \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -d '{"eventTypeProduction ": "eventTypeProduction","eventTypeStaging ": "eventTypeStaging ","branch": "${{ github.head_ref || github.ref_name }}","repository": "${{ github.event.repository.name }}","commit": "${{ github.sha }}"}'
