name: "## developing action ##"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      #      - main/*
      - main/test/*
    paths:
      - packages/api/**/*
jobs:
  confirm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Notify
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"text":"Hello, World!"}'
