name: Hello World

on: 
  workflow_dispatch:
  push:
    branches:
      - main  

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - run: echo "${{ GITHUB_REF_NAME }}"
      - run: echo "${{ GITHUB_SHA }}"