name: "## developing action ##"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      #      - main/*
      - main/test/*
    paths:
      - packages/api/**/*
jobs:
  confirm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: request to slack
        run: echo "${{ github.sha }}"
